<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net11.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>preview</LangVersion>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="BenchmarkDotNet" Version="0.13.7" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\DataFirst\DataFirst.csproj" />
      <ProjectReference Include="..\Monads\Monads.csproj" />
      <ProjectReference Include="..\TestBed\TestBed.csproj" />
    </ItemGroup>

</Project>
